apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector:
    app: hello-world-app  # This should match the label in your Deployment's pod template
  ports:
    - protocol: TCP
      port: 80         # Port that the service will expose inside the cluster
      targetPort: 80   # Port on the pod/container
      nodePort: 30080  # Exposed port on the node
  type: NodePort       # Exposes the service externally via the node
